---
- hosts: all
become: true

vars:
container_image: "staskuznetsov/petclinic"

- name: Pull Docker image PetClinic
docker_image:
name: "{{ container_image }}"
source: pull

- name: Create container
docker_container:
name: "{{ container_image }}"
image: "{{ container_image }}"
state: present
