---
- hosts: all
  become: true
  tasks:
#    - name: Pull Docker Image
#      docker_image:
#        name: "staskuznetsov/petclinic"
#        source: pull
    - name: Create container
      docker_container:
        name: "staskuznetsov/petclinic"
        image: "staskuznetsov/petclinic:latest"
        ports:
          - 8080:8080

